# Generated by Django 5.1.3 on 2024-11-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto_Comun',
            fields=[
                ('id_gasto_comun', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo_usuario', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('tipo_pago', models.IntegerField()),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.gasto_comun')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('num_piso', models.IntegerField()),
                ('descripcion_dpto', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
