# Generated by Django 5.1.3 on 2024-12-08 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo_usuario', models.CharField(max_length=64)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.gasto_comun')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='residente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.residente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='detalle_pago',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
