# Generated by Django 5.1.3 on 2024-12-08 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_departamento_usuario_residente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='gasto',
        ),
        migrations.AddField(
            model_name='gasto_comun',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto_comun',
            name='residente',
            field=models.ForeignKey(default=12312, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.residente'),
            preserve_default=False,
        ),
    ]
