# Generated by Django 5.1.3 on 2024-12-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_residente_gasto_gasto_comun_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto_comun',
            name='departamento',
        ),
        migrations.AddField(
            model_name='departamento',
            name='gastos',
            field=models.ForeignKey(default=216363728, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.gasto_comun'),
            preserve_default=False,
        ),
    ]
