# Generated by Django 5.1.3 on 2024-12-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_gasto_comun_departamento_departamento_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='gastos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.gasto_comun'),
        ),
    ]
