# Generated by Django 5.1.3 on 2024-12-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_departamento_gastos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='id_departamento',
            new_name='numero_piso',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='num_piso',
        ),
    ]
