# Generated by Django 5.1.3 on 2024-12-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_rename_id_departamento_departamento_numero_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='numero_piso',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
