# Generated by Django 5.1.3 on 2024-12-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_departamento_numero_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='num_habitaciones',
            field=models.IntegerField(default=2312312321),
            preserve_default=False,
        ),
    ]
