# Generated by Django 5.1.3 on 2024-12-09 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_departamento_gastos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='gastos',
        ),
        migrations.AddField(
            model_name='gasto_comun',
            name='residente',
            field=models.ForeignKey(default=12312, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.residente'),
            preserve_default=False,
        ),
    ]
