# Generated by Django 5.1.3 on 2024-12-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_residente_gastos_gasto_comun_residente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='residente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.residente'),
        ),
    ]
